const seedProperties=[
 {id:1,name:'The Palm House',area:'Cantonments',address:'Cantonments, Accra',bedrooms:3,baths:2,guests:6,price:185,rating:4.96,reviews:48,status:'Live',tag:'GUEST FAVOURITE',image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85',airbnb:'https://www.airbnb.com/rooms/example-palm',description:'A quiet, light-filled retreat with a private pool in one of Accra’s most coveted neighborhoods.'},
 {id:2,name:'Skyline Suite',area:'Airport Residential',address:'Airport Residential, Accra',bedrooms:2,baths:2,guests:4,price:140,rating:4.91,reviews:36,status:'Live',tag:'CITY VIEWS',image:'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=85',airbnb:'https://www.airbnb.com/rooms/example-skyline',description:'An elevated city stay with broad views, calm interiors, and fast access to Kotoka airport.'},
 {id:3,name:'The Garden Studio',area:'East Legon',address:'East Legon, Accra',bedrooms:1,baths:1,guests:2,price:95,rating:4.88,reviews:64,status:'Live',tag:'PEACEFUL ESCAPE',image:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85',airbnb:'',description:'A private garden hideaway made for slow mornings and easy access to East Legon’s restaurants.'}
];
let properties=JSON.parse(localStorage.getItem('akwaaba-properties'))||seedProperties;
let bookings=JSON.parse(localStorage.getItem('akwaaba-bookings'))||[];
let activeProperty=null;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const supportedCurrencies=['GHS','USD','EUR','GBP'];
let currency=supportedCurrencies.includes(localStorage.getItem('whosder-currency'))?localStorage.getItem('whosder-currency'):'GHS';
let exchangeRates={USD:1,GHS:12.5,EUR:.86,GBP:.74};
const currencyLocales={GHS:'en-GH',USD:'en-US',EUR:'en-IE',GBP:'en-GB'};
const money=usd=>new Intl.NumberFormat(currencyLocales[currency],{style:'currency',currency,maximumFractionDigits:currency==='GHS'?0:2}).format(usd*exchangeRates[currency]);
const persist=()=>localStorage.setItem('akwaaba-properties',JSON.stringify(properties));
const toast=msg=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
const themes=['light','dark'];
function setTheme(theme){const selected=themes.includes(theme)?theme:'light';document.documentElement.dataset.theme=selected;localStorage.setItem('akwaaba-theme',selected);$('#themeLabel').textContent=selected[0].toUpperCase()+selected.slice(1);$('#themeToggle').setAttribute('aria-label',`Current theme: ${selected}. Change color theme`)}
function setCurrency(next){currency=supportedCurrencies.includes(next)?next:'GHS';localStorage.setItem('whosder-currency',currency);$('#currencySelect').value=currency;renderProperties();if(!$('#bookingsView').classList.contains('hidden'))renderBookings()}
async function syncExchangeRates(){if(location.protocol==='file:')return;try{const response=await fetch('/api/exchange-rates',{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('FX service unavailable');const data=await response.json();if(supportedCurrencies.every(code=>Number.isFinite(data.rates?.[code])&&data.rates[code]>0)){exchangeRates={...exchangeRates,...data.rates,USD:1};setCurrency(currency)}}catch{console.info('Using cached display exchange rates. Checkout provider remains authoritative.')}}

function renderProperties(list=properties){
 $('#resultCount').textContent=`${list.length} curated ${list.length===1?'home':'homes'}`;
 $('#propertyGrid').innerHTML=list.map(p=>`<article class="property-card" data-property="${p.id}"><div class="card-image" style="background-image:url('${p.image}')"><span class="tag">${p.tag||'AVAILABLE'}</span><button class="favorite" aria-label="Save property">♡</button></div><div class="card-body"><span class="card-location">${p.area} · Accra</span><h3>${p.name}</h3><div class="card-details">${p.bedrooms} bedroom${p.bedrooms>1?'s':''} &nbsp;·&nbsp; ${p.baths} bath${p.baths>1?'s':''} &nbsp;·&nbsp; Up to ${p.guests} guests</div><div class="card-footer"><span class="rating">★ ${p.rating} <small>(${p.reviews})</small></span><span class="price">FROM <strong>${money(p.price)}</strong> / night</span></div></div></article>`).join('');
}
function route(name){
 if(!['home','bookings'].includes(name)) name='home';
 ['home','bookings'].forEach(v=>{$(`#${v}View`).classList.toggle('hidden',v!==name)}); $$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.route===name));
 if(name==='bookings')renderBookings(); window.scrollTo({top:0,behavior:'smooth'});
}
function openModal(html){$('#modalContent').innerHTML=html;$('#modalBackdrop').classList.remove('hidden')}
function closeModal(){$('#modalBackdrop').classList.add('hidden')}
function openDetail(id){
 const p=properties.find(x=>x.id===id); activeProperty=p;
 openModal(`<div class="detail-image" style="background-image:url('${p.image}')"></div><div class="detail-content"><span class="eyebrow">${p.area.toUpperCase()} · ACCRA</span><h2>${p.name}</h2><p class="detail-meta">${p.bedrooms} bedrooms · ${p.baths} baths · Up to ${p.guests} guests · ★ ${p.rating}</p><div class="detail-layout"><div><h3>Your own corner of Accra</h3><p>${p.description}</p><p>Professionally cleaned · Fast Wi-Fi · Guest support · Secure entry</p></div><form class="booking-box" id="bookingForm"><strong>${money(p.price)}</strong> <small>/ night</small><div class="date-pair"><label>CHECK IN<input required type="date" id="checkin"></label><label>CHECK OUT<input required type="date" id="checkout"></label></div><label>GUESTS<select id="bookGuests">${Array.from({length:p.guests},(_,i)=>`<option>${i+1}</option>`).join('')}</select></label><div class="cost-line"><span>Stay subtotal</span><span id="staySubtotal">Select dates</span></div><div class="cost-line total"><span>Total</span><span id="stayTotal">—</span></div><button class="primary-button wide" type="submit">Reserve & pay securely</button><p class="fx-note">Display conversion only. Your final currency and amount are confirmed by the secure payment provider.</p></form></div></div>`);
 const ci=$('#checkin'),co=$('#checkout'); const today=new Date().toISOString().slice(0,10);ci.min=today;co.min=today;
 const update=()=>{if(ci.value&&co.value){const nights=Math.ceil((new Date(co.value)-new Date(ci.value))/864e5);if(nights>0){const subtotal=nights*p.price,total=subtotal*1.08;$('#staySubtotal').textContent=`${nights} nights · ${money(subtotal)}`;$('#stayTotal').textContent=money(total);return}}$('#stayTotal').textContent='—'};ci.onchange=update;co.onchange=update;
 $('#bookingForm').onsubmit=e=>{e.preventDefault();if(new Date(co.value)<=new Date(ci.value))return toast('Check-out must be after check-in.');openPayment(p,ci.value,co.value)};
}
function openPayment(p,checkin,checkout){
 openModal(`<form class="form-grid" id="paymentForm"><h2>Complete your booking</h2><p class="full">${p.name} · ${checkin} to ${checkout}</p><label>FULL NAME<input required placeholder="Ama Mensah"></label><label>EMAIL<input required type="email" placeholder="ama@example.com"></label><div class="full"><span class="eyebrow">PAYMENT METHOD</span><div class="payment-options"><button type="button" class="pay-option selected" data-pay="Card">Credit / debit card</button><button type="button" class="pay-option" data-pay="MTN MoMo">MTN MoMo</button><button type="button" class="pay-option" data-pay="Telecel Cash">Telecel Cash</button></div><p><small>Payment details are tokenized and stored by the external payment provider, never on Whosder Ghana Stays servers.</small></p></div><label class="full"><input type="checkbox" required> I agree to the booking and cancellation terms.</label><div class="form-actions"><button type="button" class="secondary-button" data-close>Cancel</button><button class="primary-button" type="submit">Continue to secure payment →</button></div></form>`);
 let method='Card';$$('.pay-option').forEach(b=>b.onclick=()=>{$$('.pay-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');method=b.dataset.pay});
 $('#paymentForm').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);bookings.push({id:Date.now(),propertyId:p.id,checkin,checkout,method,status:'Confirmed'});localStorage.setItem('akwaaba-bookings',JSON.stringify(bookings));closeModal();toast(`Booking confirmed · paid securely with ${method}`);route('bookings')};
}
function renderBookings(){
 $('#bookingList').innerHTML=bookings.length?bookings.map(b=>{const p=properties.find(x=>x.id===b.propertyId)||seedProperties[0];return`<article class="booking-item"><img src="${p.image}" alt=""><div class="booking-copy"><span class="eyebrow">${b.status.toUpperCase()}</span><h3>${p.name}</h3><p>${b.checkin} → ${b.checkout} · ${b.method}</p><small>${p.area}, Accra</small><div class="calendar-actions"><button class="secondary-button" data-ics="${b.id}">Download .ics</button><a class="secondary-button calendar-link" target="_blank" rel="noopener noreferrer" href="${googleCalendarUrl(b,p)}">Google Calendar</a><a class="secondary-button calendar-link" target="_blank" rel="noopener noreferrer" href="${outlookCalendarUrl(b,p)}">Outlook</a></div></div></article>`}).join(''):`<div class="empty-state"><h2>No stays yet</h2><p>Your Accra plans deserve a good address. Browse the collection to begin.</p><button class="primary-button" data-route="home">Explore homes</button></div>`;
}
function calendarDates(b){return {start:b.checkin.replaceAll('-',''),end:b.checkout.replaceAll('-','')}}
function googleCalendarUrl(b,p){const d=calendarDates(b),params=new URLSearchParams({action:'TEMPLATE',text:`Stay at ${p.name}`,dates:`${d.start}/${d.end}`,details:'Confirmed Whosder Ghana Stays reservation.',location:`${p.area}, Accra, Ghana`});return `https://calendar.google.com/calendar/render?${params}`}
function outlookCalendarUrl(b,p){const params=new URLSearchParams({path:'/calendar/action/compose',rru:'addevent',subject:`Stay at ${p.name}`,startdt:b.checkin,enddt:b.checkout,body:'Confirmed Whosder Ghana Stays reservation.',location:`${p.area}, Accra, Ghana`,allday:'true'});return `https://outlook.live.com/calendar/0/deeplink/compose?${params}`}
function downloadIcs(id){const b=bookings.find(x=>x.id===id);if(!b)return;const p=properties.find(x=>x.id===b.propertyId)||seedProperties[0],d=calendarDates(b),stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const clean=s=>String(s).replace(/[\\,;]/g,m=>`\\${m}`).replace(/\n/g,'\\n');const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Whosder Ghana Stays//Booking//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH','BEGIN:VEVENT',`UID:booking-${b.id}@whosderghana.example`,`DTSTAMP:${stamp}`,`DTSTART;VALUE=DATE:${d.start}`,`DTEND;VALUE=DATE:${d.end}`,`SUMMARY:${clean(`Stay at ${p.name}`)}`,`LOCATION:${clean(`${p.area}, Accra, Ghana`)}`,'DESCRIPTION:Confirmed Whosder Ghana Stays reservation.','STATUS:CONFIRMED','END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([ics],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`whosder-ghana-stay-${b.id}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.addEventListener('click',e=>{const routeButton=e.target.closest('[data-route]');if(routeButton){e.preventDefault();route(routeButton.dataset.route)}const card=e.target.closest('[data-property]');if(card&&!e.target.closest('.favorite'))openDetail(+card.dataset.property);if(e.target.matches('[data-close]'))closeModal();if(e.target.matches('[data-ics]'))downloadIcs(+e.target.dataset.ics)});
$('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop'))closeModal()};
$('#searchForm').onsubmit=e=>{e.preventDefault();const area=$('#areaFilter').value,guests=+$(`#guestFilter`).value;renderProperties(properties.filter(p=>(!area||p.area===area)&&p.guests>=guests));document.querySelector('.content-section').scrollIntoView({behavior:'smooth'})};
$('#accountButton').onclick=()=>openModal(`<form class="form-grid" id="accountForm"><h2>Welcome to Whosder Ghana Stays</h2><p class="full">Create an account to keep your stays and provider-issued payment tokens in one place.</p><label class="full">EMAIL<input required autocomplete="email" type="email" placeholder="you@example.com"></label><label class="full">PASSWORD<input required autocomplete="new-password" type="password" minlength="12" aria-describedby="passwordHelp"></label><p class="full security-note" id="passwordHelp"><strong>Security first:</strong> use at least 12 characters. Production accounts require verified email, rate limiting, secure HttpOnly sessions, and MFA or passkeys. Whosder Ghana Stays never stores raw card or MoMo credentials.</p><div class="form-actions"><button class="primary-button" type="submit">Create secure account</button></div></form>`);
$('#themeToggle').onclick=()=>{const current=document.documentElement.dataset.theme||'light';setTheme(themes[(themes.indexOf(current)+1)%themes.length])};
$('#currencySelect').onchange=e=>setCurrency(e.target.value);
document.addEventListener('submit',e=>{if(e.target.id==='accountForm'){e.preventDefault();closeModal();toast('Account created securely')}});
setTheme(document.documentElement.dataset.theme);
setCurrency(currency);
syncExchangeRates();
